let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Casual Shirt",
    price: 45,
    desc: "Effortlessly stylish with a relaxed vibe, perfect for everyday wear.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Office Shirt",
    price: 100,
    desc: "Sleek and professional, exuding confidence with refined designs and sophisticated colors.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "T Shirt",
    price: 25,
    desc: "Comfort meets style with versatile options ranging from graphic prints to classic solids.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mens Suit",
    price: 300,
    desc: "Tailored elegance for formal occasions, commanding attention with impeccable fits and timeless designs.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Mens Tie",
    price: 25,
    desc: "Elevate your look with a touch of sophistication, featuring a range of patterns and textures to suit every style.",
    img: "images/img-5.png",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Casual shoes",
    price: 200,
    desc: "Effortlessly chic and comfortable, offering versatility for any casual outing.",
    img: "images/img-6.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "black suit",
    price: 450,
    desc: "Classic and timeless, exuding sophistication and refinement for formal events.",
    img: "images/img-7.png",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "polo shirt",
    price: 45,
    desc: "Sporty yet stylish, blending comfort with a touch of elegance for a casual yet polished look.",
    img: "images/img-8.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "denim shirt",
    price: 85,
    desc: "Effortlessly cool and ruggedly stylish, adding a laid-back charm to any outfit.",
    img: "images/img-9.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "denim pants",
    price: 120,
    desc: "Versatile and durable, offering timeless style and comfort for everyday wear.",
    img: "images/img-10.png",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "basic cap",
    price: 35,
    desc: "Classic and practical, adding a stylish finishing touch to any casual ensemble.",
    img: "images/img-11.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "leather boots",
    price: 350,
    desc: "Rugged yet refined, exuding timeless appeal and durability for any adventure.",
    img: "images/img-12.png",
  },
];
